# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/brisk-api.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("api/brisk-api.proto", :syntax => :proto3) do
    add_message "api.MachineReq" do
      optional :machine, :message, 1, "api.Machine"
    end
    add_message "api.MachineResponse" do
      optional :machine, :message, 1, "api.Machine"
    end
    add_message "api.Machine" do
      optional :ip_address, :string, 1
      optional :port, :string, 2
      optional :host_ip, :string, 3
      optional :uid, :string, 4
      optional :os_info, :string, 5
      optional :host_uid, :string, 6
      optional :image, :string, 7
      optional :type, :string, 8
      optional :state, :string, 9
      optional :region, :string, 10
      optional :cpus, :uint32, 11
      optional :memory, :uint32, 12
      optional :disk, :uint32, 13
      optional :json_data, :string, 14
      optional :id, :uint32, 15
    end
    add_message "api.GetAllProjectsReq" do
      optional :filter, :string, 1
    end
    add_message "api.GetAllProjectsResp" do
      repeated :projects, :message, 1, "api.Project"
      optional :message, :string, 2
    end
    add_message "api.InitProjectReq" do
      optional :framework, :string, 1
    end
    add_message "api.InitProjectResp" do
      optional :project, :message, 1, "api.Project"
      optional :status, :string, 2
    end
    add_message "api.WorkerRegReq" do
      optional :ip_address, :string, 1
      optional :port, :string, 2
      optional :host_ip, :string, 3
      optional :uid, :string, 4
      optional :worker_image, :string, 5
      optional :host_uid, :string, 6
    end
    add_message "api.UnreacheableReq" do
      optional :super, :message, 1, "api.Super"
      optional :projectToken, :string, 2
    end
    add_message "api.UnreachableResp" do
      optional :super, :message, 1, "api.Super"
    end
    add_message "api.WorkersReq" do
    end
    add_message "api.WorkersResp" do
      repeated :workers, :message, 1, "api.Worker"
    end
    add_message "api.SuperRegReq" do
      optional :ip_address, :string, 1
      optional :port, :string, 2
      optional :host_ip, :string, 3
      optional :sync_port, :string, 4
      optional :external_endpoint, :string, 5
      optional :sync_endpoint, :string, 6
      optional :uid, :string, 7
      optional :host_uid, :string, 8
    end
    add_message "api.WorkerReq" do
      optional :uid, :string, 1
    end
    add_message "api.ClearWorkersReq" do
      optional :supervisor_uid, :string, 1
    end
    add_message "api.ClearWorkersResp" do
      optional :status, :string, 1
    end
    add_message "api.SuperReq" do
      optional :id, :uint64, 1
    end
    add_message "api.SuperResponse" do
      optional :super, :message, 1, "api.Super"
    end
    add_message "api.CommandsRunReq" do
      optional :id, :uint64, 1
    end
    add_message "api.WorkerResponse" do
      optional :worker, :message, 1, "api.Worker"
    end
    add_message "api.GetWorkersReq" do
      optional :num_workers, :uint64, 2
      optional :worker_image, :string, 3
      optional :supervisor_uid, :string, 4
      optional :rebuild_hash, :string, 5
    end
    add_message "api.GetWorkersResp" do
      repeated :workers, :message, 1, "api.Worker"
      optional :jobrun_id, :uint32, 2
    end
    add_message "api.GetSuperReq" do
      optional :project_token, :string, 1
      optional :unique_instance_id, :string, 2
      optional :affinity, :string, 3
    end
    add_message "api.GetSuperResp" do
      optional :super, :message, 1, "api.Super"
    end
    add_message "api.Super" do
      optional :ip_address, :string, 1
      optional :port, :string, 2
      optional :state, :string, 4
      optional :endpoint, :string, 5
      optional :id, :uint64, 6
      optional :sync_port, :string, 7
      optional :sync_endpoint, :string, 8
      optional :external_endpoint, :string, 9
      optional :uid, :string, 10
      optional :setup_run_at, :string, 11
    end
    add_message "api.Worker" do
      optional :ip_address, :string, 1
      optional :port, :string, 2
      optional :build_commands_run_at, :message, 3, "google.protobuf.Timestamp"
      optional :state, :string, 4
      optional :endpoint, :string, 5
      optional :id, :uint64, 6
      optional :uid, :string, 7
      optional :host_ip, :string, 8
      optional :worker_image, :string, 9
      optional :host_uid, :string, 10
    end
    add_message "api.Project" do
      optional :name, :string, 1
      optional :project_token, :string, 2
      optional :username, :string, 3
      optional :org_id, :uint64, 4
      optional :user_id, :uint64, 5
      optional :id, :uint64, 6
      optional :concurrency, :uint64, 7
      optional :framework, :string, 8
      optional :image, :string, 9
    end
    add_message "api.GetProjectReq" do
    end
    add_message "api.FinishRunRequest" do
      optional :exit_code, :int32, 1
      optional :jobrun_id, :int32, 2
      optional :output, :string, 4
      optional :error, :string, 5
      optional :status, :enum, 6, "api.JobRunStatus"
      optional :supervisor_uid, :string, 7
      repeated :worker_run_info, :message, 8, "api.RunInfo"
    end
    add_message "api.RunInfo" do
      optional :worker_id, :uint32, 1
      optional :rebuild_hash, :string, 2
      optional :exit_code, :string, 3
      optional :output, :string, 4
      optional :finished_at, :message, 5, "google.protobuf.Timestamp"
      optional :started_at, :message, 6, "google.protobuf.Timestamp"
      optional :error, :string, 7
      repeated :files, :string, 8
    end
    add_message "api.FinishRunResponse" do
      optional :state, :string, 1
      optional :error, :string, 2
    end
    add_message "api.GetProjectResp" do
      optional :project, :message, 1, "api.Project"
    end
    add_message "api.LoginRequest" do
      optional :nonce, :string, 1
    end
    add_message "api.LoginResponse" do
      optional :url, :string, 1
      optional :description, :string, 2
      optional :status, :string, 3
      optional :credentials, :message, 4, "api.Credentials"
    end
    add_message "api.Credentials" do
      optional :api_token, :string, 1
      optional :api_key, :string, 2
    end
    add_enum "api.JobRunStatus" do
      value :completed, 0
      value :failed, 1
    end
  end
end

module Api
  MachineReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.MachineReq").msgclass
  MachineResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.MachineResponse").msgclass
  Machine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Machine").msgclass
  GetAllProjectsReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetAllProjectsReq").msgclass
  GetAllProjectsResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetAllProjectsResp").msgclass
  InitProjectReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.InitProjectReq").msgclass
  InitProjectResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.InitProjectResp").msgclass
  WorkerRegReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.WorkerRegReq").msgclass
  UnreacheableReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UnreacheableReq").msgclass
  UnreachableResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UnreachableResp").msgclass
  WorkersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.WorkersReq").msgclass
  WorkersResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.WorkersResp").msgclass
  SuperRegReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.SuperRegReq").msgclass
  WorkerReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.WorkerReq").msgclass
  ClearWorkersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.ClearWorkersReq").msgclass
  ClearWorkersResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.ClearWorkersResp").msgclass
  SuperReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.SuperReq").msgclass
  SuperResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.SuperResponse").msgclass
  CommandsRunReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.CommandsRunReq").msgclass
  WorkerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.WorkerResponse").msgclass
  GetWorkersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetWorkersReq").msgclass
  GetWorkersResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetWorkersResp").msgclass
  GetSuperReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetSuperReq").msgclass
  GetSuperResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetSuperResp").msgclass
  Super = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Super").msgclass
  Worker = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Worker").msgclass
  Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Project").msgclass
  GetProjectReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetProjectReq").msgclass
  FinishRunRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.FinishRunRequest").msgclass
  RunInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.RunInfo").msgclass
  FinishRunResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.FinishRunResponse").msgclass
  GetProjectResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.GetProjectResp").msgclass
  LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.LoginRequest").msgclass
  LoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.LoginResponse").msgclass
  Credentials = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Credentials").msgclass
  JobRunStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.JobRunStatus").enummodule
end
