# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.0.4.3'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 6.2', '>= 6.2.1'
# Use SCSS for stylesheets

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
gem 'image_processing', '~> 1.2'

gem 'haml-rails', '~> 2.0'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'derailed_benchmarks'
  gem 'faker'
  gem 'htmlbeautifier'
  gem 'mock_redis'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '~> 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'rbs'
  gem 'rufo'
  gem 'steep'
  gem 'typeprof'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'factory_bot_rails'
  gem 'gruf-rspec'
  gem 'minitest-reporters'
  gem 'rspec-rails', '~> 5.0.0'
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data' , platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'actionpack-action_caching'
gem 'devise'
gem 'gruf', '2.14.1'
gem 'responders', '~> 3.1'

gem 'rexml'
gem 'sassc-rails'
gem 'sprockets-rails', require: 'sprockets/railtie'
gem 'tailwindcss-rails', '~> 2.0'

gem 'aasm'
gem 'rack-attack', '~> 6.6'

gem 'sentry-rails'
gem 'sentry-ruby'

gem 'sidekiq', '~> 6'
gem 'sidekiq-scheduler'

gem 'kaminari'

gem 'amazing_print'
gem 'bugsnag', '~> 6.25'
gem 'lograge'
gem 'logstash-event'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-sdk'

gem 'aws-sdk-s3'
gem 'sendgrid-ruby'

gem 'rack-timeout'

gem 'connection_pool', '~> 2.3'

gem 'newrelic_rpm', '~> 9.1'

gem 'os'
gem 'redis', '~> 5.0'
gem 'redis-lock'
gem 'skylight'

gem 'omniauth-github', '~> 2.0'

gem 'omniauth-rails_csrf_protection', '~> 1.0'

gem 'omniauth-google-oauth2', '~> 1.1'
